spring.application.name=peerlink
server.port=8443

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=%dao@Z6z6+8-=43Wm:ll
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=peerlink

spring.datasource.url=jdbc:postgresql://localhost:5432/peerlink
spring.datasource.username=postgres
spring.datasource.password=S3b4st14n_04
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8

security.jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yUGVlckxpbmtBcGlBbmRJdE11c3RCZUxvbmdFbm91Z2g=
