spring.application.name=peerlink
server.port=8443

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=%dao@Z6z6+8-=43Wm:ll
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=peerlink

server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/svg+xml
server.compression.min-response-size=1024

spring.datasource.url=jdbc:postgresql://localhost:5432/peerlink
spring.datasource.username=postgres
spring.datasource.password=S3b4st14n_04
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
logging.level.org.springdoc.core.events.SpringDocAppInitializer=ERROR

spring.messages.basename=messages
spring.messages.encoding=UTF-8

peerlink.mail.enabled=true
peerlink.mail.from=no-reply@peerlink.edu.co
peerlink.mail.support-to=soporte@peerlink.edu.co

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=ce1002f50cd764
spring.mail.password=aa5227b55f67fc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

security.jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yUGVlckxpbmtBcGlBbmRJdE11c3RCZUxvbmdFbm91Z2g=
